---
ci:
    autofix_commit_msg: |
        chore(formatting): auto fixes from pre-commit hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    skip: []
    submodules: false
# Update the rev variable with the release version that you want, from the yamllint repo
# You can pass your custom .yamllint with args attribute.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: '^regex-assembly/'
      args: [--markdown-linebreak-ext=md]
- repo: local
  hooks:
    - id: run-generate
      name: run-generate
      entry: './generate.sh'
      language: script
      pass_filenames: false
      files: '^g4/'
