name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
          
      - name: Generate parser files
        run: |
          cd g4
          chmod +x generate.sh
          ./generate.sh
          cd ..
          
      - name: Run tests
        run: |
          pytest tests/ -v
          go test ./...
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            parser/*.go
            g4/*.g4
            src/seclang_parser/*.py
            README.md
            LICENSE
            go.mod
            go.sum
            pyproject.toml
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
